// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7S6418o8BzgJh-9Tl6uPqyuzAKjsh99k',
    appId: '1:673351772250:web:8b3613db08ec24616bd063',
    messagingSenderId: '673351772250',
    projectId: 'project-final-halisaha',
    authDomain: 'project-final-halisaha.firebaseapp.com',
    storageBucket: 'project-final-halisaha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgS4wBIskQrwpHTBnn3T-pDMvz2O5mHWQ',
    appId: '1:673351772250:android:8942ae51cfe1bb9f6bd063',
    messagingSenderId: '673351772250',
    projectId: 'project-final-halisaha',
    storageBucket: 'project-final-halisaha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYIZo5UCk7nNcX3vUdf8TWHjqXN2i7qA',
    appId: '1:673351772250:ios:694ab350fd17165a6bd063',
    messagingSenderId: '673351772250',
    projectId: 'project-final-halisaha',
    storageBucket: 'project-final-halisaha.firebasestorage.app',
    iosBundleId: 'com.example.projectFinalHalisaha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYIZo5UCk7nNcX3vUdf8TWHjqXN2i7qA',
    appId: '1:673351772250:ios:694ab350fd17165a6bd063',
    messagingSenderId: '673351772250',
    projectId: 'project-final-halisaha',
    storageBucket: 'project-final-halisaha.firebasestorage.app',
    iosBundleId: 'com.example.projectFinalHalisaha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7S6418o8BzgJh-9Tl6uPqyuzAKjsh99k',
    appId: '1:673351772250:web:79be51b82cd45c1f6bd063',
    messagingSenderId: '673351772250',
    projectId: 'project-final-halisaha',
    authDomain: 'project-final-halisaha.firebaseapp.com',
    storageBucket: 'project-final-halisaha.firebasestorage.app',
  );
}
